In [24]:
import numpy as np
import numpy.linalg as ln
import matplotlib.pyplot as plt

In [38]:
n = int(input())
L = np.random.uniform(-n, n, (n, n)) * 10
for i in range(n):
    L[i][i] = abs(L[i][i])
    for j in range(n):
        if (j > i) :
            L[i][j] = 0
A = L.dot(np.transpose(L))
print(A)
print(L)
L = ln.cholesky(A)
print(L)

4
[[ 1188.07137478 -1269.54388443   938.74176139  -537.00401639]
 [-1269.54388443  2833.19270171  -507.0538742    405.85922753]
 [  938.74176139  -507.0538742   1006.7200735   -122.80727938]
 [ -537.00401639   405.85922753  -122.80727938  1609.08643007]]
[[ 34.46841126   0.           0.           0.        ]
 [-36.83209751  38.42641403   0.           0.        ]
 [ 27.23484278  12.90941461   9.91616998   0.        ]
 [-15.57959873  -4.37121382  36.09563521   6.66034096]]
[[ 34.46841126   0.           0.           0.        ]
 [-36.83209751  38.42641403   0.           0.        ]
 [ 27.23484278  12.90941461   9.91616998   0.        ]
 [-15.57959873  -4.37121382  36.09563521   6.66034096]]
